### PR TITLE
Add support for flash drives reporting themselves as hard drives.

### PR DESCRIPTION
**Pull request by threebytesfull**
I picked a USB drive at random to make a bootable flash drive and came across the "doesn't detect my USB flash drive" issue. It looks like it's probably related to #29 - after comparing a few flash drives, the problem one was reporting itself as a hard drive rather than a removable drive.

It sounds like that change is a requirement for getting Windows 8 certification or something like that. Anyway, the Mac doesn't care and will boot from them so I've added a new configuration option in the experimental preferences section.

"Accept hard drives" will include these USB flash drives (and external hard drives and such too, although I haven't tested with one) and allow them to be selected. I've tested this and have successfully booted Linux with the previously unrecognised flash drive.

I haven't added translations for the new option - I'm not sure I trust Google Translate for that! ;)

### CODE REVIEW

**Comment by SevenBits** [comment]
@threebytesfull Hey there. Thanks for the contribution. First off all, it looks like line 282 in `SBAppDelegate.m` is not indented properly.

Secondly, I'm concerned about simplicity. The primary target for this application is USB drives, and I don't want the presence of any external drive to suggest to the user that these are valid installation targets... The reason I ask is because UEFI sometimes treats hard drives differently when it comes to detecting whether they are bootable.

**Comment by SevenBits** [comment]
Alright, I’ve merged this. Thanks for your contribution.

**Comment by LrsK** [comment]
This is great. When will this appear in a released version?

**Comment by SevenBits** [comment]
@LrsK Maybe within the next week or two, if I can find time to patch everything up, send all of the changed strings to the translators, etc.

**Pull request merged**
